### ISSUE TITLE
H5 file not opening

### ISSUE THREAD

**Issue by Beth96** [abyzovlab/CNVpytor#109]
Using CNVpytor version 1.0 installed in a conda environment (I don't have root privileges so can't install it any other way). I've checked I have all the required dependancies.

I am working on a non-human genome so am making my own reference genome with the following code: 

`cnvpytor -root mygenome_gc_file.pytor -gc resources/mygenome_Genome.fasta.gz -v debug -make_gc_file -log cnvpytor_gc.log 2> cnvpytor_gc.error.log`

Both the log file and error file generate the same output: 

```
cnvpytor - DEBUG - Start logging...
2022-04-04 15:14:47,608 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2022-04-04 15:14:47,609 - cnvpytor.root - DEBUG - App class init: filename 'mygenome_gc_file5.pytor'; max cores 8.
2022-04-04 15:14:47,609 - cnvpytor.io - DEBUG - Opening h5 file 'mygenome_gc_file.pytor'

```
There's no error but the programme stops (for days) until it's eventually killed by the server for taking too long.

Any suggestions would be much appreciated

**Comment by arpanda** [comment]
Could you please try latest CNVpytor, we have addressed few such issues. Please let us know if the problem exists or not.

As you are using Conda to install CNVpytor, the below command can install in the current Conda path and the only requirement is python. 

```
pip install git+https://github.com/abyzovlab/CNVpytor.git
```

Alternatively, we are working on to update the bioconda  CNVpytor version to 1.2. It will be available soon.

Thanks
Arijit

**Comment by Beth96** [comment]
Thanks for the reply, unfortunately the problem is still there even when using pip to install. 
The installation seems to have worked fine - all the required dependencies were installed except pathlib - but this should be built in to my version of python (3.8)?

**Comment by arpanda** [comment]
Could you please confirm the version. The latest version (v1.2.1) should not have the pathlib issue. Here is the command to check the version.
```
cnvpytor --verison
```

**Comment by Beth96** [comment]
Yep, it's definitely v1.2.1

**Comment by arpanda** [comment]
CNVpytor uses `pysam` library to access the fasta file. Probably its failed to open the fasta file. Somehow the log is not showing the below line of error.
```
 cnvpytor.fasta - ERROR - Problem opening file 'resources/mygenome_Genome.fasta.gz'
```

Could you please uncompress the fasta.gz file and then run `samtools faidx resources/mygenome_Genome.fasta` file to create fasta index file then run the cnvpytor command

```
cnvpytor -root mygenome_gc_file.pytor -gc resources/mygenome_Genome.fasta -v debug -make_gc_file -log cnvpytor_gc.log
```
If the error still persist, is it possible for you to share the reference genome (`resources/mygenome_Genome.fasta.gz`)? if it's publicly available, link is also fine. 

Thanks
Arijit

**Comment by Beth96** [comment]
I tried that - still have the error.
Here is the reference genome I'm using:

https://vectorbase.org/vectorbase/app/downloads/release-55/AgambiaePEST/fasta/data/

Many thanks for all your help with this!
________________________________

**Comment by arpanda** [comment]
Here is following steps, I did to process your reference genome.
```
wget https://vectorbase.org/common/downloads/release-55/AgambiaePEST/fasta/data/VectorBase-55_AgambiaePEST_Genome.fasta

cnvpytor -root mygenome_gc_file.pytor -gc VectorBase-55_AgambiaePEST_Genome.fasta -v debug -make_gc_file -log cnvpytor_gc.log
```
For me it's working fine. 

You can check this [link](https://colab.research.google.com/drive/13AkBrNX87q3ae5yhgwQFUjWGEKAYsunv?usp=sharing) as well. This link can be used to generate and download your `mygenome_gc_file.pytor` file.

Thanks
Arijit

**Comment by Beth96** [comment]
I've been following the steps exactly as you gave them to me, and I downloaded the genome file you made and created the python file with the chromosome names and length but I'm still getting the same error when I run the next step

`cnvpytor -conf mygenome_conf.py -root sample-1.pytor -rd sample-1.bam`

> 2022-04-27 23:17:34,342 - cnvpytor - DEBUG - Start logging...
> 2022-04-27 23:17:34,357 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
> 2022-04-27 23:17:34,359 - cnvpytor.genome - INFO - Reading configuration file 'mygenome_conf.py'.
> 2022-04-27 23:17:34,360 - cnvpytor.genome - INFO - Importing reference genome data: 'mm9'.
> 2022-04-27 23:17:34,360 - cnvpytor.root - DEBUG - App class init: filename 'sample-1.pytor'; max cores 8.
> 2022-04-27 23:17:34,360 - cnvpytor.io - DEBUG - Opening h5 file 'sample-1.pytor'

Any suggestions?
Thank you so much!

**Comment by arpanda** [comment]
You probably have some kind of permission issue. Could you please try to reinstall `h5py` . Here is the command
```
pip install h5py
```
and then try the same command. 

Also, if you have any other system, please try to use that.
