### ISSUE TITLE
cnvpytor.io - ERROR - Unable to open file

### ISSUE THREAD

**Issue by QianXiaobo** [abyzovlab/CNVpytor#51]
Hi,

I got error message when I run command `cnvpytor -root Z5.pytor -genotype 100`
```
2021-08-13 18:06:28,989 - cnvpytor.genome - INFO - Reading configuration file '/lustre/ref/donkey_ref_genome_conf.py'.
2021-08-13 18:06:28,990 - cnvpytor.genome - INFO - Importing reference genome data: 'dk'.
2021-08-13 18:06:31,313 - cnvpytor.io - ERROR - Unable to open file Z5.pytor!
```
And I tried other parameters like `-ls`, also got "cnvpytor.io - ERROR". I guess something wrong when using h5py read pytor file, but I can't solve it.

Could anyone help me ?
XB

**Comment by suvakov** [comment]
Can you rerun it with "-v debug" option and paste output here? Thanks

**Comment by QianXiaobo** [comment]
> Can you rerun it with "-v debug" option and paste output here? Thanks

Hi suvakov, I got the following message.
```
2021-08-28 22:46:50,575 - cnvpytor - DEBUG - Start logging...
2021-08-28 22:46:50,575 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2021-08-28 22:46:50,575 - cnvpytor.viewer - DEBUG - Viewer class init: files [Z5.pytor], params {'output_filename': '', 'chrom': [], 'panels': ['rd'], 'snp_use_mask': True, 'snp_use_id': False, 'rd_use_mask': False}.
2021-08-28 22:46:50,575 - cnvpytor.io - DEBUG - Opening h5 file 'Z5.pytor'
2021-08-28 22:46:50,609 - cnvpytor.io - DEBUG - File 'Z5.pytor' successfully opened in read-only mode.
2021-08-28 22:46:50,645 - cnvpytor.io - DEBUG - Opening h5 file '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor'
2021-08-28 22:46:50,652 - cnvpytor.io - DEBUG - File '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor' successfully opened in read-only mode.
2021-08-28 22:46:54,787 - cnvpytor.io - DEBUG - Closing h5 file '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor'
2021-08-28 22:46:54,787 - cnvpytor.io - DEBUG - Closing h5 file 'Z5.pytor'
```

**Comment by QianXiaobo** [comment]
I added the parameter **-rg** to specify the reference genome 
```cnvpytor -root Z5.pytor -rg dk -genotype 500 -v debug```
and got the ERROR can't open Z5.pytor
```
2021-08-28 23:14:31,752 - cnvpytor - DEBUG - Start logging...
2021-08-28 23:14:31,752 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2021-08-28 23:14:31,752 - cnvpytor.viewer - DEBUG - Viewer class init: files [Z5.pytor], params {'output_filename': '', 'chrom': [], 'panels': ['rd'], 'snp_use_mask': True, 'snp_use_id': False, 'rd_use_mask': False}.
2021-08-28 23:14:31,752 - cnvpytor.io - DEBUG - Opening h5 file 'Z5.pytor'
2021-08-28 23:14:31,753 - cnvpytor.io - DEBUG - File 'Z5.pytor' successfully opened in read-only mode.
2021-08-28 23:14:31,755 - cnvpytor.io - DEBUG - Opening h5 file '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor'
2021-08-28 23:14:31,766 - cnvpytor.io - DEBUG - File '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor' successfully opened in read-only mode.
2021-08-28 23:14:33,261 - cnvpytor.root - DEBUG - App class init: filename 'Z5.pytor'; max cores 8.
2021-08-28 23:14:33,261 - cnvpytor.io - DEBUG - Opening h5 file 'Z5.pytor'
2021-08-28 23:14:33,262 - cnvpytor.io - ERROR - Unable to open file Z5.pytor!
2021-08-28 23:14:33,262 - cnvpytor.io - DEBUG - Closing h5 file 'Z5.pytor'
2021-08-28 23:14:33,262 - cnvpytor.io - DEBUG - Closing h5 file '/lustre/home/lxchen/anaconda3/lib/python3.9/site-packages/cnvpytor/data/donkey_gc_file.pytor'
2021-08-28 23:14:33,263 - cnvpytor.io - DEBUG - Closing h5 file 'Z5.pytor'
```

**Comment by GENEDECODERS** [comment]
I got the same error, is there anybody can help us out?

**Comment by GENEDECODERS** [comment]
I installed the software several times, still got the same message. cnvpytor.io - ERROR - Unable to open file /media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor

**Comment by GENEDECODERS** [comment]
add -v debug
jiaxue@jiaxue32:~/CNVpytor$ cnvpytor -root /media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor -his 10000 100000 -v debug
2022-02-08 10:11:36,251 - cnvpytor - DEBUG - Start logging...
2022-02-08 10:11:36,251 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2022-02-08 10:11:36,251 - cnvpytor.root - DEBUG - App class init: filename '/media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor'; max cores 8.
2022-02-08 10:11:36,251 - cnvpytor.io - DEBUG - Opening h5 file '/media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor'
2022-02-08 10:11:36,251 - cnvpytor.io - ERROR - Unable to open file /media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor!
2022-02-08 10:11:36,251 - cnvpytor.io - DEBUG - Closing h5 file '/media/jiaxue/0B8B16F90B8B16F9/wgs/data/first.pytor'

**Comment by james-guevara** [comment]
Hi all, I got a similar error reading the mask file for hg38:

```
2022-02-11 11:09:53,449 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001990v1_decoy'.
2022-02-11 11:09:53,479 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001991v1_decoy'.
2022-02-11 11:09:53,508 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001992v1_decoy'.
2022-02-11 11:09:53,542 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001993v1_decoy'.
2022-02-11 11:09:53,571 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001994v1_decoy'.
2022-02-11 11:09:53,600 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001995v1_decoy'.
2022-02-11 11:09:53,629 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001996v1_decoy'.
2022-02-11 11:09:53,658 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001997v1_decoy'.
2022-02-11 11:09:53,687 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrUn_JTFH01001998v1_decoy'.
2022-02-11 11:09:54,702 - cnvpytor.root - INFO - Strict mask for reference genome 'hg38' found in database.
2022-02-11 11:09:54,708 - cnvpytor.io - ERROR - Unable to open file /usr/local/lib/python3.9/site-packages/cnvpytor/data/mask_hg38.pytor!
```

The file does exist:
```
Singularity> ls -lhta /usr/local/lib/python3.9/site-packages/cnvpytor/data/mask_hg38.pytor
-rw-rw-r--    1 j3guevar ddp195     13.0M Mar 28  2021 /usr/local/lib/python3.9/site-packages/cnvpytor/data/mask_hg38.pytor
```

So I'm not sure why cnvpytor is unable to open the file. I'm running it inside singularity shell if that makes any difference. I will try the `--mask` option and see if that works.

**Comment by sunjh22** [comment]
Use the first way (`git clone`) rather than `pip install` to install the latest version of cnvpytor, the problem is solved.

**Comment by JefersonSSouza** [comment]
You need to delete the **Z5.pytor** file and run again.
The algorithm checks if the named file does not exist, if it does this error will occur.

**Comment by NamSeop-Lim** [comment]
Hi all, I also had a problem with opening pytor file.

And re-installing the latest version of cnvpytor did not solve the problem.

However, I found that setting the environment variable HDF5_USE_FILE_LOCKING='FALSE' before running cnvpytor resolved the issue.

It seems that the problem is related to HDF5 file locking conflicts, especially when running cnvpytor with SLURM or in multi-threaded environments.

You can fix it by adding this line before running cnvpytor:

`export HDF5_USE_FILE_LOCKING='FALSE'`

This setting disables file locking for HDF5, which prevents conflicts when multiple processes try to access the same file simultaneously.

**Comment by GENEDECODERS** [comment]
测基因，阻遗传，就在“佳学基因”干！您的来信，已经收到！我将及时处理，同时，与您分享一些专家的临床共识，希望对您有帮助！消肿瘤，找靶向，“佳学基因”贼有效！治癌症，用化药，“佳学基因”怎么搞！ 官网：http://www.jiaxuejiyin.com
